POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Cakes for Salla",
  "author": "Cake King",
  "url": "https://www.cookinglight.com/cooking-101/techniques/cake-baking",
  "likes": 10
}