POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbGxpcyIsImlkIjoiNWNhNjI4YzhlYWY1MjYzYTVjNWI0MWM0IiwiaWF0IjoxNTU0MzkzNDI2fQ.3-bAlRcfpQ1JVlSoC69hpjOmSy9hRK84wVh_3bo7LE8

{
  "title": "Kinuskikissa",
  "author": "Joku tyyppi",
  "url": "https://www.kinuskikissa.fi",
  "likes": 10
}