POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Peggyn pieni punainen keittio",
  "author": "Peggy Thomas",
  "url": "https://pienipunainenkeittio.com/",
  "likes": 2
}