POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "sallatero",
    "password": "salainen"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
//Hae token ensin kirjautumalla login-pathissa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbGxhdGVybyIsImlkIjoiNWNhNjA2ZmNlMWE4NmUzNGNkMGNiZTc5IiwiaWF0IjoxNTU0NDU3NjA3fQ.2_gEjr1t5yA8Z4FsDuJZTgXjPn8JPC9q-PHBxEqp3Rc

{
  "title": "Annin pannarit",
  "author": "Anninen",
  "url": "https://www.anninuunissa.fi/",
  "likes": 18
}

###